///|
#deprecated
pub extend RecipeAttributes with Debug::{to_repr}

///|
#deprecated
pub extend Compilation with Debug::{to_repr}

///|
#deprecated
pub extend SemanticError with Debug::{to_repr}

///|
#deprecated
pub extend SemanticError with Eq::{not_equal, equal}

///|
#deprecated
pub extend ProjectCompilation with Debug::{to_repr}

///|
#deprecated
pub extend ProjectCompilationError with Debug::{to_repr}

///|
#deprecated
pub extend ProjectCompilationError with Eq::{not_equal, equal}

///|
#deprecated
pub extend ProjectModule with Debug::{to_repr}

///|
#deprecated
pub extend ProjectRecipe with Debug::{to_repr}

///|
#deprecated
pub extend ProjectRecipe with Eq::{not_equal, equal}

///|
#deprecated
pub extend CompiledSettings with Debug::{to_repr}

///|
#deprecated
pub extend SettingKind with Debug::{to_repr}

///|
#deprecated
pub extend SettingKind with Eq::{not_equal, equal}

///|
#deprecated
pub extend SettingSpec with Debug::{to_repr}

///|
#deprecated
pub extend SettingSpec with Eq::{not_equal, equal}

///|
#deprecated
pub extend SettingValue with Debug::{to_repr}

///|
#deprecated
pub extend SettingValue with Eq::{not_equal, equal}

///|
#deprecated
pub extend TargetOs with Debug::{to_repr}

///|
#deprecated
pub extend TargetOs with Eq::{not_equal, equal}

///|
#deprecated
pub extend TargetOs with Hash::{hash, hash_combine}

///|
#deprecated
pub extend TargetPlatform with Debug::{to_repr}

///|
#deprecated
pub extend TargetPlatform with Eq::{not_equal, equal}

///|
#deprecated
pub extend Symbol with Debug::{to_repr}

///|
#deprecated
pub extend Symbol with Eq::{not_equal, equal}

///|
#deprecated
pub extend SymbolKind with Debug::{to_repr}

///|
#deprecated
pub extend SymbolKind with Eq::{not_equal, equal}
