///|
#deprecated
pub extend ExecutionError with Debug::{to_repr}

///|
#deprecated
pub extend CacheDirective with Debug::{to_repr}

///|
#deprecated
pub extend CacheDirective with Eq::{not_equal, equal}

///|
#deprecated
pub extend CommandColor with Debug::{to_repr}

///|
#deprecated
pub extend CommandColor with Eq::{not_equal, equal}

///|
#deprecated
pub extend ConfirmationRequest with Debug::{to_repr}

///|
#deprecated
pub extend ConfirmationRequest with Eq::{not_equal, equal}

///|
#deprecated
pub extend ExecutionOptions with Debug::{to_repr}

///|
#deprecated
pub extend ExecutionOptions with Eq::{not_equal, equal}

///|
#deprecated
pub extend ExecutionPlan with Debug::{to_repr}

///|
#deprecated
pub extend ExecutionReport with Debug::{to_repr}

///|
#deprecated
pub extend ExecutionReport with Eq::{not_equal, equal}

///|
#deprecated
pub extend ExecutionTask with Debug::{to_repr}

///|
#deprecated
pub extend PlannedCommand with Debug::{to_repr}

///|
#deprecated
pub extend PlannedCommand with Eq::{not_equal, equal}

///|
#deprecated
pub extend PlannedLine with Debug::{to_repr}

///|
#deprecated
pub extend PlannedScript with Debug::{to_repr}

///|
#deprecated
pub extend PlannedScript with Eq::{not_equal, equal}

///|
#deprecated
pub extend PlannedStep with Debug::{to_repr}

///|
#deprecated
pub extend ProjectModuleRuntime with Debug::{to_repr}

///|
#deprecated
pub extend ProjectRecipeRequest with Debug::{to_repr}

///|
#deprecated
pub extend ProjectRecipeRequest with Eq::{not_equal, equal}

///|
#deprecated
pub extend RecipeRequest with Debug::{to_repr}

///|
#deprecated
pub extend RecipeRequest with Eq::{not_equal, equal}

///|
#deprecated
pub extend ScriptConfiguration with Debug::{to_repr}

///|
#deprecated
pub extend ScriptConfiguration with Eq::{not_equal, equal}
