///|
#deprecated
pub extend InvocationError with Debug::{to_repr}

///|
#deprecated
pub extend InvocationError with Eq::{not_equal, equal}

///|
#deprecated
pub extend ArgumentValue with Debug::{to_repr}

///|
#deprecated
pub extend ArgumentValue with Eq::{not_equal, equal}

///|
#deprecated
pub extend Invocation with Debug::{to_repr}

///|
#deprecated
pub extend Invocation with Eq::{not_equal, equal}

///|
#deprecated
pub extend ProjectInvocation with Debug::{to_repr}

///|
#deprecated
pub extend ProjectInvocation with Eq::{not_equal, equal}
