///|
#deprecated
pub extend Diagnostic with Debug::{to_repr}

///|
#deprecated
pub extend DiagnosticLabel with Debug::{to_repr}

///|
#deprecated
pub extend DiagnosticLabel with Eq::{not_equal, equal}

///|
#deprecated
pub extend LabelStyle with Debug::{to_repr}

///|
#deprecated
pub extend LabelStyle with Eq::{not_equal, equal}

///|
#deprecated
pub extend Severity with Debug::{to_repr}

///|
#deprecated
pub extend Severity with Eq::{not_equal, equal}

///|
#deprecated
pub extend SourceTrace with Debug::{to_repr}

///|
#deprecated
pub extend SourceTrace with Eq::{not_equal, equal}

///|
#deprecated
pub extend DiagnosticError with Debug::{to_repr}

///|
#deprecated
pub extend DiagnosticError with Eq::{not_equal, equal}
