///|
#deprecated
pub extend BuiltinCapability with Debug::{to_repr}

///|
#deprecated
pub extend BuiltinCapability with Eq::{not_equal, equal}

///|
#deprecated
pub extend BuiltinPurity with Debug::{to_repr}

///|
#deprecated
pub extend BuiltinPurity with Eq::{not_equal, equal}

///|
#deprecated
pub extend BuiltinSpec with Debug::{to_repr}

///|
#deprecated
pub extend BuiltinSpec with Eq::{not_equal, equal}

///|
#deprecated
pub extend BuiltinTarget with Debug::{to_repr}

///|
#deprecated
pub extend BuiltinTarget with Eq::{not_equal, equal}

///|
#deprecated
pub extend BuiltinError with Debug::{to_repr}

///|
#deprecated
pub extend BuiltinError with Eq::{not_equal, equal}
