///|
#deprecated
pub extend FormatterError with Debug::{to_repr}

///|
#deprecated
pub extend FormatterError with Eq::{not_equal, equal}

///|
#deprecated
pub extend CheckResult with Debug::{to_repr}

///|
#deprecated
pub extend CheckResult with Eq::{not_equal, equal}

///|
#deprecated
pub extend MarkdownError with Debug::{to_repr}

///|
#deprecated
pub extend MarkdownError with Eq::{not_equal, equal}

///|
#deprecated
pub extend MarkdownLimits with Debug::{to_repr}

///|
#deprecated
pub extend MarkdownLimits with Eq::{not_equal, equal}

///|
#deprecated
pub extend TangledSource with Debug::{to_repr}
