///|
#deprecated
pub extend ParserError with Debug::{to_repr}

///|
#deprecated
pub extend ParserError with Eq::{not_equal, equal}

///|
#deprecated
pub extend ParserConfigurationError with Debug::{to_repr}

///|
#deprecated
pub extend ParserConfigurationError with Eq::{not_equal, equal}

///|
#deprecated
pub extend ParserLimits with Debug::{to_repr}

///|
#deprecated
pub extend ParserLimits with Eq::{not_equal, equal}

///|
#deprecated
pub extend ParseReport with Debug::{to_repr}
