///|
#deprecated
pub extend CliParseError with Debug::{to_repr}

///|
#deprecated
pub extend CliParseError with Eq::{not_equal, equal}

///|
#deprecated
pub extend CommandKind with Debug::{to_repr}

///|
#deprecated
pub extend CommandKind with Eq::{not_equal, equal}

///|
#deprecated
pub extend ApplicationFailure with Debug::{to_repr}

///|
#deprecated
pub extend CliContractError with Debug::{to_repr}

///|
#deprecated
pub extend CliContractError with Eq::{not_equal, equal}

///|
#deprecated
pub extend FailureKind with Debug::{to_repr}

///|
#deprecated
pub extend FailureKind with Eq::{not_equal, equal}

///|
#deprecated
pub extend ApplicationRequest with Debug::{to_repr}

///|
#deprecated
pub extend ApplicationRequest with Eq::{not_equal, equal}

///|
#deprecated
pub extend InputSelection with Debug::{to_repr}

///|
#deprecated
pub extend InputSelection with Eq::{not_equal, equal}

///|
#deprecated
pub extend QueryKind with Debug::{to_repr}

///|
#deprecated
pub extend QueryKind with Eq::{not_equal, equal}

///|
#deprecated
pub extend ApplicationResponse with Debug::{to_repr}

///|
#deprecated
pub extend ApplicationResponse with Eq::{not_equal, equal}
