///|
#deprecated
pub extend PathError with Eq::{not_equal, equal}

///|
#deprecated
pub extend PathError with Debug::{to_repr}

///|
#deprecated
pub extend PathFlavor with Eq::{not_equal, equal}

///|
#deprecated
pub extend PathFlavor with Hash::{hash, hash_combine}

///|
#deprecated
pub extend PathFlavor with Debug::{to_repr}

///|
#deprecated
pub extend PathValue with Eq::{not_equal, equal}

///|
#deprecated
pub extend PathValue with Hash::{hash, hash_combine}

///|
#deprecated
pub extend PathValue with Debug::{to_repr}
