///|
#deprecated
pub extend DelimiterKind with Debug::{to_repr}

///|
#deprecated
pub extend DelimiterKind with Eq::{not_equal, equal}

///|
#deprecated
pub extend LexerError with Debug::{to_repr}

///|
#deprecated
pub extend LexerError with Eq::{not_equal, equal}

///|
#deprecated
pub extend Keyword with Debug::{to_repr}

///|
#deprecated
pub extend Keyword with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
#deprecated
pub extend Keyword with Eq::{not_equal, equal}

///|
#deprecated
pub extend Keyword with Hash::{hash, hash_combine}

///|
#deprecated
pub extend LexerConfigurationError with Debug::{to_repr}

///|
#deprecated
pub extend LexerConfigurationError with Eq::{not_equal, equal}

///|
#deprecated
pub extend LexerLimits with Debug::{to_repr}

///|
#deprecated
pub extend LexerLimits with Eq::{not_equal, equal}

///|
#deprecated
pub extend Token with Debug::{to_repr}

///|
#deprecated
pub extend Token with Eq::{not_equal, equal}

///|
#deprecated
pub extend TokenKind with Debug::{to_repr}

///|
#deprecated
pub extend TokenKind with Compare::{op_lt, op_le, op_ge, compare, op_gt}

///|
#deprecated
pub extend TokenKind with Eq::{not_equal, equal}

///|
#deprecated
pub extend TokenKind with Hash::{hash, hash_combine}

///|
#deprecated
pub extend TokenStream with Debug::{to_repr}
