///|
#deprecated
pub extend EnvironmentConfigError with Debug::{to_repr}

///|
#deprecated
pub extend EnvironmentConfigError with Eq::{not_equal, equal}

///|
#deprecated
pub extend PlatformConfiguration with Debug::{to_repr}

///|
#deprecated
pub extend PlatformConfiguration with Eq::{not_equal, equal}

///|
#deprecated
pub extend ShellConfiguration with Debug::{to_repr}

///|
#deprecated
pub extend ShellConfiguration with Eq::{not_equal, equal}

///|
#deprecated
pub extend TemporaryDirectoryConfiguration with Debug::{to_repr}

///|
#deprecated
pub extend TemporaryDirectoryConfiguration with Eq::{not_equal, equal}

///|
#deprecated
pub extend TemporaryDirectorySource with Debug::{to_repr}

///|
#deprecated
pub extend TemporaryDirectorySource with Eq::{not_equal, equal}

///|
#deprecated
pub extend DotenvError with Debug::{to_repr}

///|
#deprecated
pub extend DotenvError with Eq::{not_equal, equal}

///|
#deprecated
pub extend EnvNameMode with Debug::{to_repr}

///|
#deprecated
pub extend EnvNameMode with Eq::{not_equal, equal}
