///|
#deprecated
pub extend LoaderError with Debug::{to_repr}

///|
#deprecated
pub extend LoaderError with Eq::{not_equal, equal}

///|
#deprecated
pub extend GraphLimits with Debug::{to_repr}

///|
#deprecated
pub extend GraphLimits with Eq::{not_equal, equal}

///|
#deprecated
pub extend LoadedGraph with Debug::{to_repr}

///|
#deprecated
pub extend LoadedSource with Debug::{to_repr}

///|
#deprecated
pub extend SearchOptions with Debug::{to_repr}

///|
#deprecated
pub extend SearchOptions with Eq::{not_equal, equal}

///|
#deprecated
pub extend SourceRelation with Debug::{to_repr}

///|
#deprecated
pub extend SourceRelation with Eq::{not_equal, equal}
