///|
#deprecated
pub extend BinaryOperator with Debug::{to_repr}

///|
#deprecated
pub extend BinaryOperator with Eq::{not_equal, equal}

///|
#deprecated
pub extend Expression with Debug::{to_repr}

///|
#deprecated
pub extend Expression with Eq::{not_equal, equal}

///|
#deprecated
pub extend FormatPart with Debug::{to_repr}

///|
#deprecated
pub extend FormatPart with Eq::{not_equal, equal}

///|
#deprecated
pub extend StringKind with Debug::{to_repr}

///|
#deprecated
pub extend StringKind with Eq::{not_equal, equal}

///|
#deprecated
pub extend StringLiteral with Debug::{to_repr}

///|
#deprecated
pub extend StringLiteral with Eq::{not_equal, equal}

///|
#deprecated
pub extend UnaryOperator with Debug::{to_repr}

///|
#deprecated
pub extend UnaryOperator with Eq::{not_equal, equal}

///|
#deprecated
pub extend Alias with Debug::{to_repr}

///|
#deprecated
pub extend Alias with Eq::{not_equal, equal}

///|
#deprecated
pub extend Assignment with Debug::{to_repr}

///|
#deprecated
pub extend Assignment with Eq::{not_equal, equal}

///|
#deprecated
pub extend Ast with Debug::{to_repr}

///|
#deprecated
pub extend Ast with Eq::{not_equal, equal}

///|
#deprecated
pub extend Attribute with Debug::{to_repr}

///|
#deprecated
pub extend Attribute with Eq::{not_equal, equal}

///|
#deprecated
pub extend AttributeArgument with Debug::{to_repr}

///|
#deprecated
pub extend AttributeArgument with Eq::{not_equal, equal}

///|
#deprecated
pub extend Dependency with Debug::{to_repr}

///|
#deprecated
pub extend Dependency with Eq::{not_equal, equal}

///|
#deprecated
pub extend FunctionDefinition with Debug::{to_repr}

///|
#deprecated
pub extend FunctionDefinition with Eq::{not_equal, equal}

///|
#deprecated
pub extend FunctionParameter with Debug::{to_repr}

///|
#deprecated
pub extend FunctionParameter with Eq::{not_equal, equal}

///|
#deprecated
pub extend Import with Debug::{to_repr}

///|
#deprecated
pub extend Import with Eq::{not_equal, equal}

///|
#deprecated
pub extend Item with Debug::{to_repr}

///|
#deprecated
pub extend Item with Eq::{not_equal, equal}

///|
#deprecated
pub extend Module with Debug::{to_repr}

///|
#deprecated
pub extend Module with Eq::{not_equal, equal}

///|
#deprecated
pub extend Parameter with Debug::{to_repr}

///|
#deprecated
pub extend Parameter with Eq::{not_equal, equal}

///|
#deprecated
pub extend Recipe with Debug::{to_repr}

///|
#deprecated
pub extend Recipe with Eq::{not_equal, equal}

///|
#deprecated
pub extend RecipeFragment with Debug::{to_repr}

///|
#deprecated
pub extend RecipeFragment with Eq::{not_equal, equal}

///|
#deprecated
pub extend RecipeLine with Debug::{to_repr}

///|
#deprecated
pub extend RecipeLine with Eq::{not_equal, equal}

///|
#deprecated
pub extend Setting with Debug::{to_repr}

///|
#deprecated
pub extend Setting with Eq::{not_equal, equal}
