///|
#deprecated
pub extend EvaluationContext with Debug::{to_repr}

///|
#deprecated
pub extend EvaluationContext with Eq::{not_equal, equal}

///|
#deprecated
pub extend EffectShell with Debug::{to_repr}

///|
#deprecated
pub extend EffectShell with Eq::{not_equal, equal}

///|
#deprecated
pub extend Environment with Debug::{to_repr}

///|
#deprecated
pub extend EvaluationError with Debug::{to_repr}

///|
#deprecated
pub extend EvaluationError with Eq::{not_equal, equal}

///|
#deprecated
pub extend EvaluationLimits with Debug::{to_repr}

///|
#deprecated
pub extend EvaluationLimits with Eq::{not_equal, equal}

///|
#deprecated
pub extend FunctionEnvironment with Debug::{to_repr}

///|
#deprecated
pub extend LazyState with Debug::{to_repr}

///|
#deprecated
pub extend LazyState with Eq::{not_equal, equal}
