///|
#deprecated
pub extend CacheError with Debug::{to_repr}

///|
#deprecated
pub extend CacheError with Eq::{not_equal, equal}

///|
#deprecated
pub extend CacheKey with Debug::{to_repr}

///|
#deprecated
pub extend CacheKey with Eq::{not_equal, equal}

///|
#deprecated
pub extend CacheManifest with Debug::{to_repr}

///|
#deprecated
pub extend CacheManifest with Eq::{not_equal, equal}

///|
#deprecated
pub extend InputDigest with Debug::{to_repr}

///|
#deprecated
pub extend InputDigest with Eq::{not_equal, equal}
